#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../lib/nats_streamer"

Sync do
  config = NatsStreamer::Config.new(YAML.load(File.read(ARGV[0]), symbolize_names: true))
  NatsStreamer::Application.new(config:).run
end
